### ISSUE TITLE
Request new icons for Robot Blue Dark theme

### ISSUE THREAD

**Issue by eriskar** [SethStormR/Robot#1]
I love the Robot Blue Dark theme, and I use it every time I install/re-install the OS.

If it is possible, could you create icons for the following applications?

* RStudio
* 1Password
* VMWare Horizon Client
* Zotero
* Github Desktop
* Cisco Secure Client
* Calculator
* Text Editor (Gedit)/Notepad Next
* Pop!_Shop

Really appreciate your work! Thank you.

**Comment by SethStormR** [comment]
Sure, I'll get done for the next patch.

**Comment by eriskar** [comment]
Thank you so much! I appreciate it a lot.

**Comment by SethStormR** [comment]
VMWare Horizon Client has static icon, which means you have to set it manually. I'll put hte static icons in and folder called "Extra".

![screenshot-2024-09-18-11-11-24](https://github.com/user-attachments/assets/0c7e258b-7e11-4b82-944d-6e5cda39bd47)

**Comment by eriskar** [comment]
Yes, indeed, and I used your "preferences-desktop-wallpaper.svg" since it was the one most closely resembling the VMWare Horizon original icon.

**Comment by SethStormR** [comment]
Can I get you to check the icon names for "Cisco Secure Client" as I'm not intended to buy it ;)
Also which calculator are we talking about. There's 100s of calculator apps for Linux :)

**Comment by SethStormR** [comment]
ops, wrong button.

**Comment by eriskar** [comment]
I could just set the icons manually if you provide the icon for calculator for example :) But here you go:

com.ciscosecureclient.gui.desktop - NAME: Cisco Secure Client
rstudio.desktop - NAME: RStudio
1password.desktop - NAME: 1Password
vmware-view.desktop - NAME: VMware Horizon Client
zotero.desktop - NAME: Zotero
github-desktop - NAME: GitHub Desktop
org.gnome.Calculator.desktop - NAME: Calculator
org.gnome.gedit.desktop - NAME: Text Editor

I was unable to find the Pop!_Shop in /usr/share/applications..

**Comment by SethStormR** [comment]
The Pop!Shop is just call pop-shop :).
Check back in ~2 hours time tops and I have them ready.

**Comment by eriskar** [comment]
Wonderful!! Thank you so much :) You're an everyday hero!

**Comment by eriskar** [comment]
I know I closed this but just downloaded the new version and it works perfectly. Thank you! You just made my week :)
